# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='key.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\tkey.proto\")\n\tPrime_key\x12\x0c\n\x04\x62\x61se\x18\x01 \x02(\x06\x12\x0e\n\x06public\x18\x02 \x02(\x06\"\x19\n\nPublic_key\x12\x0b\n\x03key\x18\x01 \x02(\x06')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PRIME_KEY = _descriptor.Descriptor(
  name='Prime_key',
  full_name='Prime_key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='Prime_key.base', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='public', full_name='Prime_key.public', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=54,
)


_PUBLIC_KEY = _descriptor.Descriptor(
  name='Public_key',
  full_name='Public_key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Public_key.key', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['Prime_key'] = _PRIME_KEY
DESCRIPTOR.message_types_by_name['Public_key'] = _PUBLIC_KEY

Prime_key = _reflection.GeneratedProtocolMessageType('Prime_key', (_message.Message,), dict(
  DESCRIPTOR = _PRIME_KEY,
  __module__ = 'key_pb2'
  # @@protoc_insertion_point(class_scope:Prime_key)
  ))
_sym_db.RegisterMessage(Prime_key)

Public_key = _reflection.GeneratedProtocolMessageType('Public_key', (_message.Message,), dict(
  DESCRIPTOR = _PUBLIC_KEY,
  __module__ = 'key_pb2'
  # @@protoc_insertion_point(class_scope:Public_key)
  ))
_sym_db.RegisterMessage(Public_key)


# @@protoc_insertion_point(module_scope)
